### ISSUE TITLE
While in-game; cannot close Global MOTD

### ISSUE THREAD

**Issue by waterandroid** [Bazoo-/BazHUD#15]
Steps to reproduce:
1. Pause while in-game
2. Open the Global MOTD (the orange button)
3. Attempt to close it, by clicking the button again
The image demonstrates how highlighting over the button shows the Resume Game Label.
![2015-03-02_00002](https://cloud.githubusercontent.com/assets/6828778/6455863/08ed5b0c-c128-11e4-820e-a1709cf0c9ea.jpg)

**Comment by Bazooo** [comment]
thanks! I just fixed it.

Closing the issue
